### ISSUE TITLE
Improve Readability

### ISSUE THREAD

**Issue by nakaz** [aukai84/Network-Broadcast-News#1]
Let's clean up your spacings to improve readability of your code.

Code that is enclosed should be 1 tab or 2/4 spaces in to represent that it belongs to the encapsulating function or block. 

Bring this back 1 tab or 2 spaces. 
https://github.com/aukai84/Network-Broadcast-News/blob/master/server.js#L10-L22

This function could be put on the bottom so appears separate and its own self rather than being in the middle of all your `socket` declarations. 
https://github.com/aukai84/Network-Broadcast-News/blob/master/server.js#L16-L22

If you aren't using the `counter` best not to use it otherwise its just adding an extra line to read and your counting something thats not being used. 
https://github.com/aukai84/Network-Broadcast-News/blob/master/server.js#L29

**Comment by aukai84** [comment]
fixed issues
